{ "display_name":"Metricproxy",
  "description": "SignalFx Metricproxy",
  "project_url": "https://github.com/signalfx/integrations/tree/master/metricproxy",
  "code": "https://github.com/signalfx/metricproxy",
  "featured": false,
  "logo_large": "/images/repos/metricproxy/img/integrations_metricproxy.png",
  "logo_small": "/images/repos/metricproxy/img/integrations_metricproxy%402x.png"
}
