{ "display_name":"Memcached collectd plugin",
  "description": "Memcached collectd plugin",
  "project_url": "https://github.com/signalfx/integrations/tree/master/collectd-memcached",
  "code": "https://github.com/signalfx/collectd/blob/master/src/memcached.c",
  "featured": false,
  "logo_large": "/images/repos/collectd-memcached/img/integrations_memcached.png",
  "logo_small": "/images/repos/collectd-memcached/img/integrations_memcached%402x.png"
},
