{ "display_name":"Memory collectd plugin",
  "description": "The Memory plugin collects physical memory utilization.",
  "project_url": "https://github.com/signalfx/integrations/tree/master/collectd-memory",
  "code": "https://github.com/signalfx/collectd/blob/master/src/memory.c",
  "featured": false,
  "logo_large": "/images/repos/collectd-memory/img/integrations_collectd%402x.png",
  "logo_small": "/images/repos/collectd-memory/img/integrations_collectd.png"
},
