{ "display_name":"ZooKeeper collectd plugin",
  "description": "ZooKeeper collectd plugin",
  "project_url": "https://github.com/signalfx/integrations/tree/master/collectd-zookeeper",
  "code": "https://github.com/signalfx/collectd/blob/master/src/zookeeper.c",
  "featured": false,
  "logo_large": "/images/repos/collectd-zookeeper/img/integrations_zookeeper.png",
  "logo_small": "/images/repos/collectd-zookeeper/img/integrations_zookeeper%402x.png"
}
