{ "display_name":"NGINX collectd plugin",
  "description": "NGINX collectd plugin",
  "project_url": "https://github.com/signalfx/integrations/tree/master/collectd-nginx",
  "code": "https://github.com/signalfx/collectd/blob/master/src/nginx.c",
  "featured": false,
  "logo_large": "/images/repos/collectd-nginx/img/integrations_nginx.png",
  "logo_small": "/images/repos/collectd-nginx/img/integrations_nginx%402x.png"
},
