{ "display_name":"Elasticsearch collectd plugin",
  "description": "Elasticsearch collectd plugin",
  "project_url": "https://github.com/signalfx/integrations/tree/master/collectd-elasticsearch",
  "code": "https://github.com/signalfx/collectd-elasticsearch",
  "featured": true,
  "logo_large": "/images/repos/collectd-elasticsearch/img/integrations_elasticsearch.png",
  "logo_small": "/images/repos/collectd-elasticsearch/img/integrations_elasticsearch%402x.png"
},
