{ "display_name":"SignalFx Java Library",
  "description": "Java Library for SignalFx",
  "project_url": "https://github.com/signalfx/integrations/tree/master/lib-java",
  "code": "https://github.com/signalfx/golib/tree/master/sfxclient",
  "featured": false,
  "logo_large": "/images/repos/lib-java/img/integrations_java.png",
  "logo_small": "/images/repos/lib-java/img/integrations_java%402x.png"
}
