{ "display_name":"Perfcounter Reporter",
  "description": "SignalFx Integration for Windows Perfcounter",
  "project_url": "https://github.com/signalfx/integrations/tree/master/win-perfcounter",
  "code": "https://github.com/signalfx/PerfCounterReporter",
  "featured": false,
  "logo_large": "/images/repos/win-perfcounter/img/integrations_windows.png",
  "logo_small": "/images/repos/win-perfcounter/img/integrations_windows%402x.png"
}
