{ "display_name":"Apache collectd plugin",
  "description": "Apache collectd plugin",
  "project_url": "https://github.com/signalfx/integrations/tree/master/collectd-apache",
  "code": "https://github.com/signalfx/collectd/blob/master/src/apache.c",
  "featured": false,
  "logo_large": "/images/repos/collectd-apache/img/integrations_apache%402x.png",
  "logo_small": "/images/repos/collectd-apache/img/integrations_apache.png"
},
