{ "display_name":"DF (Disk Free) plugin",
  "description": "The DF plugin collects file system usage information, i. e. basically how much space on a mounted partition is used and how much is available. ",
  "project_url": "https://github.com/signalfx/integrations/tree/master/collectd-df",
  "code": "https://github.com/signalfx/collectd/blob/master/src/df.c",
  "featured": false,
  "logo_large": "/images/repos/collectd/img/integrations_collectd%402x.png",
  "logo_small": "/images/repos/collectd/img/integrations_collectd.png"
},
