{ "display_name":"Kafka collectd plugin",
  "description": "Kafka collectd plugin",
  "project_url": "https://github.com/signalfx/integrations/tree/master/collectd-kafka",
  "code": "https://github.com/signalfx/collectd/blob/master/src/write_kafka.c",
  "featured": true,
  "logo_large": "/images/repos/collectd-kafka/img/integrations_kafka.png",
  "logo_small": "/images/repos/collectd-kafka/img/integrations_kafka%402x.png"
},
