{ "display_name":"SignalFx collectd plugin",
  "description": "SignalFx collectd plugin",
  "project_url": "https://github.com/signalfx/integrations/tree/master/collectd-signalfx",
  "code": "https://github.com/signalfx/collectd-signalfx",
  "featured": false,
  "logo_large": "/images/repos/collectd-signalfx/img/integrations_signalfx-collectd-plugin.png",
  "logo_small": "/images/repos/collectd-signalfx/img/integrations_signalfx-collectd-plugin%402x.png"
},
