{ "display_name":"RabbitMQ collectd plugin",
  "description": "RabbitMQ collectd plugin",
  "project_url": "https://github.com/signalfx/integrations/tree/master/collectd-rabbitmq",
  "code": "https://github.com/signalfx/collectd-rabbitmq",
  "featured": false,
  "logo_large": "/images/repos/collectd-rabbitmq/img/integrations_rabbitmq.png",
  "logo_small": "/images/repos/collectd-rabbitmq/img/integrations_rabbitmq%402x.png"
},
