{ "display_name":"SignalFx collectd agent",
  "description": "SignalFx validated version of collectd",
  "project_url": "https://github.com/signalfx/integrations/tree/master/collectd",
  "code": "https://github.com/signalfx/collectd",
  "featured": true,
  "logo_large": "/images/repos/collectd/img/integrations_collectd%402x.png",
  "logo_small": "/images/repos/collectd/img/integrations_collectd.png"
},
