{ "display_name":"StatsD collectd plugin",
  "description": "The StatsD plugin pulls metrics and statistics from StatsD into collectd",
  "project_url": "https://github.com/signalfx/integrations/tree/master/collectd-statsd",
  "code": "https://github.com/signalfx/collectd/blob/master/src/statsd.c",
  "featured": false,
  "logo_large": "/images/repos/collectd-statsd/img/integrations_collectd%402x.png",
  "logo_small": "/images/repos/collectd-statsd/img/integrations_collectd.png"
},
